name=Patchugo_Core
version=1.0.0
author=Innuvatech
maintainer=Innuvatech <andrea.rantin@Innuvatech.com>
sentence=Patchugo Core library for all Patchugo products
paragraph=This library provides all foundational functionalities such as status codes and logging
category=Device Control
url=https://github.com/Innuvatech/Patchugo_Core
architectures=*
includes=patchugo_core.h